import Head from 'next/head'

import Card from "../component/card";

import styles from '../styles/Home.module.css'

import sedans from "../public/icon-sedans.svg";
import suvs from "../public/icon-suvs.svg";
import luxury from "../public/icon-luxury.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>3-column preview card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className={styles.main}>
        <Card />
      </main>
    </div>
  )
}
